-- ============================================
-- INSERTAR 365 FRASES DEL DÍA
-- ============================================
-- Ejecutar en Supabase SQL Editor
-- ============================================

-- Limpiar frases existentes (opcional)
-- DELETE FROM daily_phrases;

INSERT INTO daily_phrases (text, author, active) VALUES
  ('Recuerda que si tú me amas, yo te amo más', NULL, true),
  ('Eres mi razón para sonreír cada mañana', NULL, true),
  ('Contigo quiero envejecer, ver el mundo y reírnos de todo', NULL, true),
  ('Tu sonrisa ilumina mis días más oscuros', NULL, true),
  ('Cada día a tu lado es un regalo que no merezco', NULL, true),
  ('Eres mi hogar, mi paz y mi aventura', NULL, true),
  ('Cuando estás triste, recuerda que tienes a alguien que te ama infinitamente', NULL, true),
  ('Tu felicidad es mi felicidad', NULL, true),
  ('Eres la mejor parte de mi día, todos los días', NULL, true),
  ('Contigo quiero construir todos mis sueños', NULL, true),
  ('Tu amor me hace sentir que puedo con todo', NULL, true),
  ('Eres mi persona favorita en todo el universo', NULL, true),
  ('Cuando te veo, todo tiene sentido', NULL, true),
  ('Eres hermosa, inteligente y perfecta tal como eres', NULL, true),
  ('Tu risa es la música más bonita que conozco', NULL, true),
  ('Contigo quiero ver todos los atardeceres del mundo', NULL, true),
  ('Eres mi todo, mi razón y mi destino', NULL, true),
  ('Cuando estés triste, aquí estaré para abrazarte', NULL, true),
  ('Tu amor me hace mejor persona cada día', NULL, true),
  ('Eres la estrella que guía mis noches', NULL, true),
  ('Contigo quiero vivir mil vidas', NULL, true),
  ('Tu presencia hace que todo sea más bonito', NULL, true),
  ('Eres mi refugio seguro en este mundo loco', NULL, true),
  ('Cuando pienso en ti, solo puedo sonreír', NULL, true),
  ('Tu amor es el mejor regalo que he recibido', NULL, true),
  ('Eres perfecta en tus imperfecciones', NULL, true),
  ('Contigo quiero envejecer riendo', NULL, true),
  ('Tu mirada me dice todo lo que necesito saber', NULL, true),
  ('Eres mi razón para creer en el amor verdadero', NULL, true),
  ('Cuando estés triste, recuerda que eres amada profundamente', NULL, true),
  ('Tu sonrisa es mi droga favorita', NULL, true),
  ('Eres la mejor decisión que he tomado en mi vida', NULL, true),
  ('Contigo quiero compartir todos mis secretos', NULL, true),
  ('Tu amor me llena de energía y esperanza', NULL, true),
  ('Eres mi compañera de aventuras y de calma', NULL, true),
  ('Cuando te abrazo, siento que estoy en casa', NULL, true),
  ('Tu amor me hace sentir invencible', NULL, true),
  ('Eres la luz que ilumina mi camino', NULL, true),
  ('Contigo quiero hacer memoria de todo', NULL, true),
  ('Tu presencia hace que el tiempo se detenga', NULL, true),
  ('Eres mi mejor amiga y mi gran amor', NULL, true),
  ('Cuando estés triste, aquí estaré para hacerte reír', NULL, true),
  ('Tu amor me da fuerzas para seguir adelante', NULL, true),
  ('Eres la persona más importante de mi vida', NULL, true),
  ('Contigo quiero aprender y crecer juntos', NULL, true),
  ('Tu risa es contagiosa y hermosa', NULL, true),
  ('Eres mi paz en medio del caos', NULL, true),
  ('Cuando te veo, siento que todo está bien', NULL, true),
  ('Tu amor me hace sentir especial', NULL, true),
  ('Eres mi sueño hecho realidad', NULL, true),
  ('Contigo quiero construir una vida llena de risas', NULL, true),
  ('Tu sonrisa puede cambiar mi día completo', NULL, true),
  ('Eres mi razón para ser mejor cada día', NULL, true),
  ('Cuando estés triste, recuerda que tienes a alguien que te adora', NULL, true),
  ('Tu amor es mi mayor tesoro', NULL, true),
  ('Eres perfecta tal como eres, sin cambiar nada', NULL, true),
  ('Contigo quiero compartir todos mis miedos y sueños', NULL, true),
  ('Tu presencia hace que todo sea más fácil', NULL, true),
  ('Eres mi compañera de vida y de locuras', NULL, true),
  ('Cuando te abrazo, siento que puedo con todo', NULL, true),
  ('Tu amor me hace sentir completo', NULL, true),
  ('Eres la mejor parte de mi historia', NULL, true),
  ('Contigo quiero ver el mundo y reírnos de todo', NULL, true),
  ('Tu mirada me dice que todo va a estar bien', NULL, true),
  ('Eres mi refugio cuando el mundo es demasiado', NULL, true),
  ('Cuando estés triste, aquí estaré para consolarte', NULL, true),
  ('Tu amor me da esperanza en los días grises', NULL, true),
  ('Eres mi persona favorita para todo', NULL, true),
  ('Contigo quiero envejecer siendo felices', NULL, true),
  ('Tu sonrisa es lo primero que quiero ver cada día', NULL, true),
  ('Eres mi razón para creer en los milagros', NULL, true),
  ('Cuando te veo, siento que el amor existe', NULL, true),
  ('Tu amor me hace sentir que soy suficiente', NULL, true),
  ('Eres la mejor decisión que he tomado', NULL, true),
  ('Contigo quiero hacer todos mis planes realidad', NULL, true),
  ('Tu risa es música para mis oídos', NULL, true),
  ('Eres mi paz y mi tormenta perfecta', NULL, true),
  ('Cuando estés triste, recuerda que eres increíblemente amada', NULL, true),
  ('Tu amor me hace sentir que puedo volar', NULL, true),
  ('Eres mi compañera de vida y de risas', NULL, true),
  ('Contigo quiero compartir todos mis momentos', NULL, true),
  ('Tu presencia hace que todo tenga sentido', NULL, true),
  ('Eres mi mejor amiga y mi gran amor a la vez', NULL, true),
  ('Cuando te abrazo, siento que estoy completo', NULL, true),
  ('Tu amor me da fuerzas para enfrentar cualquier cosa', NULL, true),
  ('Eres la luz que necesito en los días oscuros', NULL, true),
  ('Contigo quiero construir recuerdos hermosos', NULL, true),
  ('Tu sonrisa puede iluminar cualquier habitación', NULL, true),
  ('Eres mi razón para sonreír sin motivo', NULL, true),
  ('Cuando estés triste, aquí estaré para hacerte feliz', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado', NULL, true),
  ('Eres perfecta en cada detalle', NULL, true),
  ('Contigo quiero vivir todas las aventuras', NULL, true),
  ('Tu mirada me dice que todo va a salir bien', NULL, true),
  ('Eres mi hogar, mi lugar seguro', NULL, true),
  ('Cuando te veo, siento que el mundo es hermoso', NULL, true),
  ('Tu amor me hace sentir invencible y vulnerable a la vez', NULL, true),
  ('Eres la mejor parte de mi día', NULL, true),
  ('Contigo quiero envejecer siendo jóvenes de corazón', NULL, true),
  ('Tu risa es la mejor medicina para mi alma', NULL, true),
  ('Eres mi razón para creer en el amor eterno', NULL, true),
  ('Cuando estés triste, recuerda que tienes a alguien que te ama sin condiciones', NULL, true),
  ('Tu amor me hace sentir que puedo lograr todo', NULL, true),
  ('Eres mi compañera de vida y de sueños', NULL, true),
  ('Contigo quiero compartir todos mis secretos y locuras', NULL, true),
  ('Tu presencia hace que todo sea más bonito y fácil', NULL, true),
  ('Eres mi mejor amiga, mi amor y mi todo', NULL, true),
  ('Cuando te abrazo, siento que el tiempo se detiene', NULL, true),
  ('Tu amor me da esperanza en los días difíciles', NULL, true),
  ('Eres la persona más importante de mi mundo', NULL, true),
  ('Contigo quiero hacer memoria de cada momento', NULL, true),
  ('Tu sonrisa es mi felicidad diaria', NULL, true),
  ('Eres mi razón para ser mejor persona', NULL, true),
  ('Cuando estés triste, aquí estaré para abrazarte fuerte', NULL, true),
  ('Tu amor me hace sentir que soy suficiente y más', NULL, true),
  ('Eres perfecta en tu forma única de ser', NULL, true),
  ('Contigo quiero construir una vida llena de amor', NULL, true),
  ('Tu risa es contagiosa y hermosa como tú', NULL, true),
  ('Eres mi paz en medio de la tormenta', NULL, true),
  ('Cuando te veo, siento que todo está en su lugar', NULL, true),
  ('Tu amor me hace sentir que puedo con todo', NULL, true),
  ('Eres mi sueño que se hizo realidad', NULL, true),
  ('Contigo quiero compartir todos mis planes y locuras', NULL, true),
  ('Tu mirada me dice que somos perfectos juntos', NULL, true),
  ('Eres mi refugio cuando el mundo es demasiado ruidoso', NULL, true),
  ('Cuando estés triste, recuerda que eres increíblemente especial', NULL, true),
  ('Tu amor me da fuerzas para seguir adelante siempre', NULL, true),
  ('Eres mi compañera de aventuras y de calma', NULL, true),
  ('Contigo quiero envejecer riendo y amando', NULL, true),
  ('Tu sonrisa puede cambiar cualquier día gris', NULL, true),
  ('Eres mi razón para creer en el amor verdadero y puro', NULL, true),
  ('Cuando te abrazo, siento que estoy en el lugar correcto', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado del mundo', NULL, true),
  ('Eres la mejor parte de mi historia personal', NULL, true),
  ('Contigo quiero ver todos los atardeceres y amaneceres', NULL, true),
  ('Tu presencia hace que todo tenga más sentido', NULL, true),
  ('Eres mi mejor amiga, mi amor y mi compañera de vida', NULL, true),
  ('Cuando estés triste, aquí estaré para hacerte sonreír', NULL, true),
  ('Tu amor me da esperanza en cada amanecer', NULL, true),
  ('Eres la persona más importante de mi existencia', NULL, true),
  ('Contigo quiero hacer memoria de cada risa y cada lágrima', NULL, true),
  ('Tu risa es la música más bonita que conozco', NULL, true),
  ('Eres mi razón para sonreír sin motivo aparente', NULL, true),
  ('Cuando te veo, siento que el amor es real', NULL, true),
  ('Tu amor me hace sentir que puedo lograr cualquier cosa', NULL, true),
  ('Eres perfecta tal como eres, sin necesidad de cambiar', NULL, true),
  ('Contigo quiero construir todos mis sueños y planes', NULL, true),
  ('Tu mirada me dice que somos perfectos el uno para el otro', NULL, true),
  ('Eres mi hogar, mi paz y mi lugar seguro', NULL, true),
  ('Cuando estés triste, recuerda que tienes a alguien que te adora completamente', NULL, true),
  ('Tu amor me hace sentir que soy suficiente y valioso', NULL, true),
  ('Eres mi compañera de vida y de todas las locuras', NULL, true),
  ('Contigo quiero compartir todos mis secretos y miedos', NULL, true),
  ('Tu presencia hace que todo sea más bonito y especial', NULL, true),
  ('Eres mi mejor amiga, mi amor y mi todo en uno', NULL, true),
  ('Cuando te abrazo, siento que puedo con todo el mundo', NULL, true),
  ('Tu amor me da fuerzas para enfrentar cualquier desafío', NULL, true),
  ('Eres la luz que ilumina mis días más oscuros', NULL, true),
  ('Contigo quiero envejecer siendo felices y jóvenes de corazón', NULL, true),
  ('Tu sonrisa es lo primero que quiero ver cada mañana', NULL, true),
  ('Eres mi razón para creer en los milagros del amor', NULL, true),
  ('Cuando estés triste, aquí estaré para consolarte y hacerte reír', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado', NULL, true),
  ('Eres la mejor decisión que he tomado en toda mi vida', NULL, true),
  ('Contigo quiero hacer todos mis planes y sueños realidad', NULL, true),
  ('Tu risa es contagiosa, hermosa y perfecta como tú', NULL, true),
  ('Eres mi paz en medio del caos de la vida', NULL, true),
  ('Cuando te veo, siento que todo está bien en el mundo', NULL, true),
  ('Tu amor me hace sentir que puedo volar y tocar el cielo', NULL, true),
  ('Eres mi compañera de vida, de risas y de lágrimas', NULL, true),
  ('Contigo quiero compartir todos mis momentos especiales', NULL, true),
  ('Tu presencia hace que el tiempo se detenga y sea perfecto', NULL, true),
  ('Eres mi mejor amiga, mi gran amor y mi compañera de aventuras', NULL, true),
  ('Cuando estés triste, recuerda que eres amada profundamente', NULL, true),
  ('Tu amor me da esperanza en los días más difíciles', NULL, true),
  ('Eres la persona más importante de mi vida y mi corazón', NULL, true),
  ('Contigo quiero hacer memoria de cada momento especial', NULL, true),
  ('Tu sonrisa puede iluminar cualquier día, por más gris que sea', NULL, true),
  ('Eres mi razón para ser mejor persona cada día', NULL, true),
  ('Cuando te abrazo, siento que estoy en el lugar más seguro del mundo', NULL, true),
  ('Tu amor me hace sentir que soy suficiente y valioso', NULL, true),
  ('Eres perfecta en tu forma única y especial de ser', NULL, true),
  ('Contigo quiero construir una vida llena de amor y risas', NULL, true),
  ('Tu risa es la mejor medicina para cualquier mal día', NULL, true),
  ('Eres mi paz cuando el mundo es demasiado ruidoso', NULL, true),
  ('Cuando estés triste, aquí estaré para abrazarte y hacerte feliz', NULL, true),
  ('Tu amor me da fuerzas para seguir adelante sin importar qué', NULL, true),
  ('Eres mi compañera de vida y de todos los sueños', NULL, true),
  ('Contigo quiero envejecer riendo, amando y siendo felices', NULL, true),
  ('Tu mirada me dice que somos perfectos juntos', NULL, true),
  ('Eres mi refugio cuando el mundo es demasiado para mí', NULL, true),
  ('Cuando te veo, siento que el amor verdadero existe', NULL, true),
  ('Tu amor me hace sentir que puedo lograr cualquier cosa que me proponga', NULL, true),
  ('Eres la mejor parte de mi historia y mi futuro', NULL, true),
  ('Contigo quiero ver el mundo y reírnos de todo juntos', NULL, true),
  ('Tu sonrisa es mi felicidad diaria y mi razón para sonreír', NULL, true),
  ('Eres mi razón para creer en el amor eterno y verdadero', NULL, true),
  ('Cuando estés triste, recuerda que tienes a alguien que te ama sin límites', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado del universo', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas y de todo', NULL, true),
  ('Contigo quiero compartir todos mis secretos, miedos y sueños', NULL, true),
  ('Tu presencia hace que todo tenga más sentido y sea más bonito', NULL, true),
  ('Eres mi mejor amiga, mi amor y mi compañera de todas las aventuras', NULL, true),
  ('Cuando te abrazo, siento que puedo con todo el mundo y más', NULL, true),
  ('Tu amor me da esperanza en cada amanecer y en cada atardecer', NULL, true),
  ('Eres la persona más importante de mi existencia y mi corazón', NULL, true),
  ('Contigo quiero hacer memoria de cada risa, cada lágrima y cada momento', NULL, true),
  ('Tu risa es la música más bonita y contagiosa que conozco', NULL, true),
  ('Eres mi razón para sonreír sin motivo y ser feliz siempre', NULL, true),
  ('Cuando te veo, siento que el amor es real y verdadero', NULL, true),
  ('Tu amor me hace sentir que puedo lograr cualquier cosa que me proponga', NULL, true),
  ('Eres perfecta tal como eres, sin necesidad de cambiar absolutamente nada', NULL, true),
  ('Contigo quiero construir todos mis sueños, planes y aventuras', NULL, true),
  ('Tu mirada me dice que somos perfectos el uno para el otro', NULL, true),
  ('Eres mi hogar, mi paz, mi lugar seguro y mi todo', NULL, true),
  ('Cuando estés triste, recuerda que eres increíblemente amada y especial', NULL, true),
  ('Tu amor me hace sentir que soy suficiente, valioso y amado', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas y de sueños', NULL, true),
  ('Contigo quiero envejecer siendo felices, jóvenes de corazón y riendo', NULL, true),
  ('Tu sonrisa es lo primero que quiero ver cada mañana y lo último cada noche', NULL, true),
  ('Eres mi razón para creer en los milagros del amor y de la vida', NULL, true),
  ('Cuando estés triste, aquí estaré para consolarte, abrazarte y hacerte feliz', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado del mundo y del universo', NULL, true),
  ('Eres la mejor decisión que he tomado en toda mi vida y mi existencia', NULL, true),
  ('Contigo quiero hacer todos mis planes, sueños y aventuras realidad', NULL, true),
  ('Tu risa es contagiosa, hermosa, perfecta y única como tú', NULL, true),
  ('Eres mi paz en medio del caos, la tormenta y el ruido de la vida', NULL, true),
  ('Cuando te veo, siento que todo está bien en el mundo y en mi corazón', NULL, true),
  ('Tu amor me hace sentir que puedo volar, tocar el cielo y lograr todo', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas, de sueños y de todo', NULL, true),
  ('Contigo quiero compartir todos mis momentos especiales, secretos y locuras', NULL, true),
  ('Tu presencia hace que el tiempo se detenga y sea perfecto en cada instante', NULL, true),
  ('Eres mi mejor amiga, mi gran amor y mi compañera de todas las aventuras', NULL, true),
  ('Cuando estés triste, recuerda que eres amada profundamente y sin condiciones', NULL, true),
  ('Tu amor me da esperanza en los días más difíciles y en los más felices', NULL, true),
  ('Eres la persona más importante de mi vida, mi corazón y mi existencia', NULL, true),
  ('Contigo quiero hacer memoria de cada momento especial, risa y lágrima', NULL, true),
  ('Tu sonrisa puede iluminar cualquier día, por más gris, triste o difícil que sea', NULL, true),
  ('Eres mi razón para ser mejor persona cada día, cada hora y cada minuto', NULL, true),
  ('Cuando te abrazo, siento que estoy en el lugar más seguro y perfecto del mundo', NULL, true),
  ('Tu amor me hace sentir que soy suficiente, valioso, amado y especial', NULL, true),
  ('Eres perfecta en tu forma única, especial y hermosa de ser', NULL, true),
  ('Contigo quiero construir una vida llena de amor, risas, aventuras y felicidad', NULL, true),
  ('Tu risa es la mejor medicina para cualquier mal día, tristeza o problema', NULL, true),
  ('Eres mi paz cuando el mundo es demasiado ruidoso, caótico o difícil', NULL, true),
  ('Cuando estés triste, aquí estaré para abrazarte fuerte, consolarte y hacerte feliz', NULL, true),
  ('Tu amor me da fuerzas para seguir adelante sin importar qué, cuándo o cómo', NULL, true),
  ('Eres mi compañera de vida, de todos los sueños, planes y aventuras', NULL, true),
  ('Contigo quiero envejecer riendo, amando, siendo felices y jóvenes de corazón', NULL, true),
  ('Tu mirada me dice que somos perfectos juntos, el uno para el otro, siempre', NULL, true),
  ('Eres mi refugio cuando el mundo es demasiado para mí, cuando todo es difícil', NULL, true),
  ('Cuando te veo, siento que el amor verdadero existe, es real y es para siempre', NULL, true),
  ('Tu amor me hace sentir que puedo lograr cualquier cosa que me proponga en la vida', NULL, true),
  ('Eres la mejor parte de mi historia pasada, presente y futura', NULL, true),
  ('Contigo quiero ver el mundo, reírnos de todo, vivir aventuras y ser felices', NULL, true),
  ('Tu sonrisa es mi felicidad diaria, mi razón para sonreír y mi todo', NULL, true),
  ('Eres mi razón para creer en el amor eterno, verdadero, puro y para siempre', NULL, true),
  ('Cuando estés triste, recuerda que tienes a alguien que te ama sin límites ni condiciones', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado del universo, del mundo y de la vida', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas, de sueños, de planes y de todo', NULL, true),
  ('Contigo quiero compartir todos mis secretos, miedos, sueños, locuras y momentos', NULL, true),
  ('Tu presencia hace que todo tenga más sentido, sea más bonito, especial y perfecto', NULL, true),
  ('Eres mi mejor amiga, mi amor, mi compañera de todas las aventuras y mi todo', NULL, true),
  ('Cuando te abrazo, siento que puedo con todo el mundo, el universo y más allá', NULL, true),
  ('Tu amor me da esperanza en cada amanecer, cada atardecer y cada momento del día', NULL, true),
  ('Eres la persona más importante de mi existencia, mi corazón, mi alma y mi vida', NULL, true),
  ('Contigo quiero hacer memoria de cada risa, cada lágrima, cada momento y cada instante', NULL, true),
  ('Tu risa es la música más bonita, contagiosa, hermosa y perfecta que conozco', NULL, true),
  ('Eres mi razón para sonreír sin motivo, ser feliz siempre y disfrutar la vida', NULL, true),
  ('Cuando te veo, siento que el amor es real, verdadero, puro y para siempre', NULL, true),
  ('Tu amor me hace sentir que puedo lograr cualquier cosa que me proponga en la vida', NULL, true),
  ('Eres perfecta tal como eres, sin necesidad de cambiar absolutamente nada de ti', NULL, true),
  ('Contigo quiero construir todos mis sueños, planes, aventuras y momentos especiales', NULL, true),
  ('Tu mirada me dice que somos perfectos el uno para el otro, siempre y para siempre', NULL, true),
  ('Eres mi hogar, mi paz, mi lugar seguro, mi refugio y mi todo en este mundo', NULL, true),
  ('Cuando estés triste, recuerda que eres increíblemente amada, especial y valiosa', NULL, true),
  ('Tu amor me hace sentir que soy suficiente, valioso, amado, especial y perfecto', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas, de sueños y de todas las aventuras', NULL, true),
  ('Contigo quiero envejecer siendo felices, jóvenes de corazón, riendo y amando', NULL, true),
  ('Tu sonrisa es lo primero que quiero ver cada mañana y lo último que quiero ver cada noche', NULL, true),
  ('Eres mi razón para creer en los milagros del amor, de la vida y de la felicidad', NULL, true),
  ('Cuando estés triste, aquí estaré para consolarte, abrazarte fuerte y hacerte feliz', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado del mundo, del universo y de la vida', NULL, true),
  ('Eres la mejor decisión que he tomado en toda mi vida, mi existencia y mi corazón', NULL, true),
  ('Contigo quiero hacer todos mis planes, sueños, aventuras y momentos especiales realidad', NULL, true),
  ('Tu risa es contagiosa, hermosa, perfecta, única y especial como tú eres', NULL, true),
  ('Eres mi paz en medio del caos, la tormenta, el ruido y las dificultades de la vida', NULL, true),
  ('Cuando te veo, siento que todo está bien en el mundo, en mi corazón y en mi alma', NULL, true),
  ('Tu amor me hace sentir que puedo volar, tocar el cielo, lograr todo y ser feliz', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas, de sueños, de planes y de todo', NULL, true),
  ('Contigo quiero compartir todos mis momentos especiales, secretos, locuras y aventuras', NULL, true),
  ('Tu presencia hace que el tiempo se detenga y sea perfecto en cada instante y momento', NULL, true),
  ('Eres mi mejor amiga, mi gran amor, mi compañera de todas las aventuras y mi todo', NULL, true),
  ('Cuando estés triste, recuerda que eres amada profundamente, sin condiciones ni límites', NULL, true),
  ('Tu amor me da esperanza en los días más difíciles, más felices y en todos los días', NULL, true),
  ('Eres la persona más importante de mi vida, mi corazón, mi alma, mi existencia y mi todo', NULL, true),
  ('Contigo quiero hacer memoria de cada momento especial, risa, lágrima, instante y segundo', NULL, true),
  ('Tu sonrisa puede iluminar cualquier día, por más gris, triste, difícil o complicado que sea', NULL, true),
  ('Eres mi razón para ser mejor persona cada día, cada hora, cada minuto y cada segundo', NULL, true),
  ('Cuando te abrazo, siento que estoy en el lugar más seguro, perfecto y hermoso del mundo', NULL, true),
  ('Tu amor me hace sentir que soy suficiente, valioso, amado, especial, perfecto y único', NULL, true),
  ('Eres perfecta en tu forma única, especial, hermosa y perfecta de ser quien eres', NULL, true),
  ('Contigo quiero construir una vida llena de amor, risas, aventuras, felicidad y momentos especiales', NULL, true),
  ('Tu risa es la mejor medicina para cualquier mal día, tristeza, problema o dificultad', NULL, true),
  ('Eres mi paz cuando el mundo es demasiado ruidoso, caótico, difícil o complicado para mí', NULL, true),
  ('Cuando estés triste, aquí estaré para abrazarte fuerte, consolarte, hacerte reír y ser feliz', NULL, true),
  ('Tu amor me da fuerzas para seguir adelante sin importar qué, cuándo, cómo o por qué', NULL, true),
  ('Eres mi compañera de vida, de todos los sueños, planes, aventuras y momentos especiales', NULL, true),
  ('Contigo quiero envejecer riendo, amando, siendo felices, jóvenes de corazón y disfrutando', NULL, true),
  ('Tu mirada me dice que somos perfectos juntos, el uno para el otro, siempre y para siempre', NULL, true),
  ('Eres mi refugio cuando el mundo es demasiado para mí, cuando todo es difícil o complicado', NULL, true),
  ('Cuando te veo, siento que el amor verdadero existe, es real, es puro y es para siempre', NULL, true),
  ('Tu amor me hace sentir que puedo lograr cualquier cosa que me proponga en la vida y más', NULL, true),
  ('Eres la mejor parte de mi historia pasada, presente, futura y de toda mi existencia', NULL, true),
  ('Contigo quiero ver el mundo, reírnos de todo, vivir aventuras, ser felices y disfrutar', NULL, true),
  ('Tu sonrisa es mi felicidad diaria, mi razón para sonreír, mi todo y mi razón de ser', NULL, true),
  ('Eres mi razón para creer en el amor eterno, verdadero, puro, perfecto y para siempre', NULL, true),
  ('Cuando estés triste, recuerda que tienes a alguien que te ama sin límites, condiciones ni restricciones', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado del universo, del mundo, de la vida y de todo', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas, de sueños, de planes, de aventuras y de todo', NULL, true),
  ('Contigo quiero compartir todos mis secretos, miedos, sueños, locuras, momentos y aventuras', NULL, true),
  ('Tu presencia hace que todo tenga más sentido, sea más bonito, especial, perfecto y hermoso', NULL, true),
  ('Eres mi mejor amiga, mi amor, mi compañera de todas las aventuras, de la vida y mi todo', NULL, true),
  ('Cuando te abrazo, siento que puedo con todo el mundo, el universo, la vida y más allá', NULL, true),
  ('Tu amor me da esperanza en cada amanecer, cada atardecer, cada momento y cada instante del día', NULL, true),
  ('Eres la persona más importante de mi existencia, mi corazón, mi alma, mi vida y mi todo', NULL, true),
  ('Contigo quiero hacer memoria de cada risa, cada lágrima, cada momento, cada instante y cada segundo', NULL, true),
  ('Tu risa es la música más bonita, contagiosa, hermosa, perfecta, única y especial que conozco', NULL, true),
  ('Eres mi razón para sonreír sin motivo, ser feliz siempre, disfrutar la vida y ser positivo', NULL, true),
  ('Cuando te veo, siento que el amor es real, verdadero, puro, perfecto, eterno y para siempre', NULL, true),
  ('Tu amor me hace sentir que puedo lograr cualquier cosa que me proponga en la vida, el mundo y más', NULL, true),
  ('Eres perfecta tal como eres, sin necesidad de cambiar absolutamente nada de ti, de tu esencia', NULL, true),
  ('Contigo quiero construir todos mis sueños, planes, aventuras, momentos especiales y mi futuro', NULL, true),
  ('Tu mirada me dice que somos perfectos el uno para el otro, siempre, para siempre y eternamente', NULL, true),
  ('Eres mi hogar, mi paz, mi lugar seguro, mi refugio, mi calma y mi todo en este mundo', NULL, true),
  ('Cuando estés triste, recuerda que eres increíblemente amada, especial, valiosa, única y perfecta', NULL, true),
  ('Tu amor me hace sentir que soy suficiente, valioso, amado, especial, perfecto, único y completo', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas, de sueños, de aventuras y de todas las cosas', NULL, true),
  ('Contigo quiero envejecer siendo felices, jóvenes de corazón, riendo, amando y disfrutando juntos', NULL, true),
  ('Tu sonrisa es lo primero que quiero ver cada mañana y lo último que quiero ver cada noche, siempre', NULL, true),
  ('Eres mi razón para creer en los milagros del amor, de la vida, de la felicidad y de la eternidad', NULL, true),
  ('Cuando estés triste, aquí estaré para consolarte, abrazarte fuerte, hacerte reír y ser completamente feliz', NULL, true),
  ('Tu amor me hace sentir que soy el más afortunado del mundo, del universo, de la vida y de toda la existencia', NULL, true),
  ('Eres la mejor decisión que he tomado en toda mi vida, mi existencia, mi corazón, mi alma y mi todo', NULL, true),
  ('Contigo quiero hacer todos mis planes, sueños, aventuras, momentos especiales y mi futuro realidad', NULL, true),
  ('Tu risa es contagiosa, hermosa, perfecta, única, especial, increíble y maravillosa como tú eres', NULL, true),
  ('Eres mi paz en medio del caos, la tormenta, el ruido, las dificultades y las complicaciones de la vida', NULL, true),
  ('Cuando te veo, siento que todo está bien en el mundo, en mi corazón, en mi alma y en mi existencia', NULL, true),
  ('Tu amor me hace sentir que puedo volar, tocar el cielo, lograr todo, ser feliz y conquistar el mundo', NULL, true),
  ('Eres mi compañera de vida, de risas, de lágrimas, de sueños, de planes, de aventuras y de absolutamente todo', NULL, true),
  ('Contigo quiero compartir todos mis momentos especiales, secretos, locuras, aventuras y todas mis experiencias', NULL, true),
  ('Tu presencia hace que el tiempo se detenga y sea perfecto en cada instante, momento y segundo de la vida', NULL, true),
  ('Eres mi mejor amiga, mi gran amor, mi compañera de todas las aventuras, de la vida y mi todo completo', NULL, true),
  ('Cuando estés triste, recuerda que eres amada profundamente, sin condiciones, sin límites y sin restricciones', NULL, true),
  ('Tu amor me da esperanza en los días más difíciles, más felices, más complicados y en todos los días', NULL, true),
  ('Eres la persona más importante de mi vida, mi corazón, mi alma, mi existencia, mi mundo y mi todo', NULL, true),
  ('Contigo quiero hacer memoria de cada momento especial, risa, lágrima, instante, segundo y cada experiencia', NULL, true),
  ('Tu sonrisa puede iluminar cualquier día, por más gris, triste, difícil, complicado o desafiante que sea', NULL, true),
  ('Eres mi razón para ser mejor persona cada día, cada hora, cada minuto, cada segundo y en cada momento', NULL, true),
  ('Cuando te abrazo, siento que estoy en el lugar más seguro, perfecto, hermoso y especial del mundo y del universo', NULL, true),
  ('Tu amor me hace sentir que soy suficiente, valioso, amado, especial, perfecto, único, completo y maravilloso', NULL, true),
  ('Eres perfecta en tu forma única, especial, hermosa, perfecta y maravillosa de ser quien eres y como eres', NULL, true),
  ('Contigo quiero construir una vida llena de amor, risas, aventuras, felicidad, momentos especiales y eternidad', NULL, true),
  ('Tu risa es la mejor medicina para cualquier mal día, tristeza, problema, dificultad o complicación de la vida', NULL, true),
  ('Eres mi todo, mi razón de ser, mi felicidad, mi paz, mi amor, mi vida y mi eternidad completa y perfecta', NULL, true);

-- Verificar: SELECT COUNT(*) FROM daily_phrases WHERE active = true;
-- Debe retornar 365
